name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v1

      - name: Node 14
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: npm install and npm run build
        run: |
          cd frontend
          npm ci
          npm run build:ci
